-- MySQL Script generated by MySQL Workbench
-- Thu Mar 25 15:09:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemacontroleestoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemacontroleestoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemacontroleestoque` DEFAULT CHARACTER SET utf8 ;
USE `sistemacontroleestoque` ;

-- -----------------------------------------------------
-- Table `sistemacontroleestoque`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacontroleestoque`.`usuarios` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacontroleestoque`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacontroleestoque`.`produtos` (
  `idproduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` BIGINT UNSIGNED NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
